# Generated by Django 4.2 on 2024-03-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_reviews_movie_alter_reviews_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='movies.genre', verbose_name='жанры'),
        ),
    ]
