# Generated by Django 4.2 on 2024-03-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='url',
            field=models.SlugField(max_length=160),
        ),
    ]
